AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  serverless-gitops

  Sample SAM Template for serverless-gitops

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

Resources:
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /healt
            Method: GET

Outputs:
  RestApi:
    Description: "API Gateway endpoint URL for Prod stage for  function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"