AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  REST API used to interact with GitHub and implement a GitOps Solution with AWS Serverless tools.

Globals:
  Function:
    Timeout: 3
    Runtime: nodejs10.x

Resources:
  HealthCheckFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.handler
      Events:
        Request:
          Type: Api
          Properties:
            Path: /health
            Method: GET

Outputs:
  RestApi:
    Description: "API Gateway endpoint URL for Prod stage for GitOps"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"