AWSTemplateFormatVersion: '2010-09-09'
Description: >
  DynamoDB Table to store solutions PR information.

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: 'Id'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'Id'
          KeyType: 'HASH'
      TableName: 'gitops-registry'
      Tags:
        - Key: Project
          Value: GitOps
        - Key: User
          Value: GitOps